(defun main (first second)
  (let ((bulls 0)
        (cows 0))
    (dotimes (i 4)
      (dotimes (j 4)
        (when (equal (elt first i) (elt second j))
          (if (= i j)
              (incf bulls)
              (incf cows)))))
    (cons bulls cows)))
